### ISSUE TITLE
Issue with setting boundary conditions in parallel

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#106]
```
(UW) benknight@Bens-MacBook-Pro Working % mpiexec -np 2 python3 Ex_Stokes_Sinker_Linear.py
Stokes: Jacobians complete, now compile
Stokes: Compilation complete, Now set residuals
Stokes:                      Now set jacobians
Setting bc 0 (dirichlet)
 - components: [0 1]
 - boundary:   ['Top' 'Bottom']
 - fn:         Matrix([[0], [0]]) 
Traceback (most recent call last):
  File "/Users/benknight/Documents/Research/Github/UW3-benchmarks/Working/Ex_Stokes_Sinker_Linear.py", line 225, in <module>
    stokes.solve(zero_init_guess=True)
  File "underworld3/cython/petsc_generic_snes_solvers.pyx", line 1395, in underworld3.cython.generic_solvers.SNES_Stokes.solve
  File "underworld3/cython/petsc_generic_snes_solvers.pyx", line 1346, in underworld3.cython.generic_solvers.SNES_Stokes._setup_terms
IndexError: index 0 is out of bounds for axis 0 with size 0
```

The associated lines of code from 'underworld3/cython/petsc_generic_snes_solvers.pyx' are:

```
for boundary in bc.boundaries:
    label = self.dm.getLabel(boundary)
    if not label:
        if self.verbose == True:
            print(f"Discarding bc {boundary} which has no corresponding mesh / dm label")
        continue

    iset = label.getNonEmptyStratumValuesIS()
    if iset:
        value = iset.getIndices()[0]  # this is only one value in the label ...  <--- line 1346
        ind = value
```

**Comment by lmoresi** [comment]
I'm onto that one ... my bad !

**Comment by bknight1** [comment]
closing as this has been fixed
