### ISSUE TITLE
Cython 3.x error propagation

### ISSUE THREAD

**Issue by adigitoleo** [underworldcode/underworld3-archive#150]
Hello,

I'd like to flag a build failure with Cython>=3 (2023) which results from a change in Cython's error propagation handling. A relevant excerpt of `PETSC_DIR=/path/to/my/petsc PETSC_ARCH=arch-linux-c-debug pip install -e .` is included here:

<details><summary>Log (click to view)</summary>

```
    Petsc version: 3.20.4
    warning: underworld3/cython/petsc_discretisation.pyx:13:38: Unknown type declaration 'double' in annotation, ignoring
    warning: underworld3/cython/petsc_discretisation.pyx:35:117: Unknown type declaration 'double' in annotation, ignoring

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                    if bc.type == 'neumann':
                        bc_type = 6
                    else:
                        bc_type = 5

                    PetscDSAddBoundary_UW( cdm.dm, bc_type, str(boundary).encode('utf8'), str(boundary).encode('utf8'), 0, comps_view.shape[0], <const PetscInt *> &comps_view[0], <void (*)()>ext.fns_bcs[index], NULL, 1, <const PetscInt *> &ind, NULL)
                                                                                                                                                                                   ^
    ------------------------------------------------------------

    underworld3/cython/petsc_generic_snes_solvers.pyx:327:175: Cannot assign type 'void (*)(void) except *' to 'void (*)(void) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void) except *'.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                    if bc.type == 'neumann':
                        bc_type = 6
                    else:
                        bc_type = 5

                    PetscDSAddBoundary_UW( cdm.dm, bc_type, str(boundary).encode('utf8'), str(boundary).encode('utf8'), 0, comps_view.shape[0], <const PetscInt *> &comps_view[0], <void (*)()>ext.fns_bcs[index], NULL, 1, <const PetscInt *> &ind, NULL)
                                                                                                                                                                                   ^
    ------------------------------------------------------------

    underworld3/cython/petsc_generic_snes_solvers.pyx:733:175: Cannot assign type 'void (*)(void) except *' to 'void (*)(void) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void) except *'.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                    if bc.type == 'neumann':
                        bc_type = 6
                    else:
                        bc_type = 5

                    PetscDSAddBoundary_UW(cdm.dm, bc_type, str(boundary).encode('utf8'), str(boundary).encode('utf8'), 0, comps_view.shape[0], <const PetscInt *> &comps_view[0], <void (*)()>ext.fns_bcs[index], NULL, 1, <const PetscInt *> &ind, NULL)
                                                                                                                                                                                  ^
    ------------------------------------------------------------

    underworld3/cython/petsc_generic_snes_solvers.pyx:1325:174: Cannot assign type 'void (*)(void) except *' to 'void (*)(void) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void) except *'.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                        bc_type = 5


                    PetscDSAddBoundary_UW(cdm.dm, bc_type, str(boundary).encode('utf8'), str(boundary).encode('utf8'),
                        0, comps_view.shape[0], <const PetscInt *> &comps_view[0],
                        <void (*)()>ext.fns_bcs[index], NULL, 1, <const PetscInt *> &ind, NULL)
                        ^
    ------------------------------------------------------------

    underworld3/cython/petsc_generic_snes_solvers.pyx:1906:20: Cannot assign type 'void (*)(void) except *' to 'void (*)(void) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void) except *'.
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/leon/vcs/underworld3/setup.py", line 160, in <module>
        ext_modules=cythonize(
                    ^^^^^^^^^^
      File "/home/leon/vcs/underworld3/.venv-underworld3/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
        cythonize_one(*args)
      File "/home/leon/vcs/underworld3/.venv-underworld3/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: underworld3/cython/petsc_generic_snes_solvers.pyx
```

</details>

This particular change for Cython 3 is noted [here](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept). More information [here](https://cython.readthedocs.io/en/stable/src/userguide/language_basics.html#error-return-values).

A temporary workaround is available by using a compiler directive:

```diff
diff --git a/setup.py b/setup.py
index f35855c8..9805c3ff 100644
--- a/setup.py
+++ b/setup.py
@@ -159,7 +159,7 @@ setup(
     },
     ext_modules=cythonize(
         extensions,
-        compiler_directives={"language_level": "3"},  # or "2" or "3str"
+        compiler_directives={"legacy_implicit_noexcept": True, "language_level": "3"},  # or "2" or "3str"
         build_dir="build",
         annotate=True,
         # gdb_debug=True,
```

**Comment by julesghub** [comment]
Hi @adigitoleo,
With the recent PR (development -> main) this cython compilation error doesn't occur. The offending arguments have been changed to be cast as `noexcept` to match the function arguments.
Thanks for alerting us to this and for your suggested fix.
Closing this issue. Feel free to reopen.
