### ISSUE TITLE
AttributeError: `underworld3` has no attribute `__version__` during setup

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld3-archive#244]
Description: While running `python setup.py develop` for `underworld3,` I encountered an `AttributeError` due to the missing `__version__` attribute in the `underworld3` module.

System Details:

Operating System: macOS (arm)
Python Version: 3.11
PETSc Version: 3.21.1
Virtual Environment: venv
Underworld3 Git Branch: development

Steps to Reproduce:
1. Create and activate a virtual environment: python -m venv venv_uw3
2. Clone the underworld3 repository and switch to the development branch.
3. Run the following command:
`python setup.py develop`

The error occurs during the Cythonization of various files.
Error Output:
```
Traceback (most recent call last):
  File "/path/to/site-packages/setuptools/config/expand.py", line 80, in __getattr__
    return next(
           ^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/underworld3/setup.py", line 163, in <module>
    setup(
  File "/path/to/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/path/to/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/path/to/site-packages/setuptools/dist.py", line 627, in parse_config_files
    setupcfg.parse_configuration(
  File "/path/to/site-packages/setuptools/config/setupcfg.py", line 190, in parse_configuration
    meta.parse()
  File "/path/to/site-packages/setuptools/config/setupcfg.py", line 501, in parse
    section_parser_method(section_options)
  File "/path/to/site-packages/setuptools/config/setupcfg.py", line 418, in _parse_attr
    return expand.read_attr(attr_desc, package_dir, root_dir)
  File "/path/to/site-packages/setuptools/config/expand.py", line 196, in read_attr
    return getattr(module, attr_name)
AttributeError: module 'underworld3' has no attribute '__version__'
```

**Comment by bknight1** [comment]
Might be due to this change:

https://github.com/underworldcode/underworld3/blame/275e624ab979f821494592b45a06b582985e5e63/setup.cfg#L3

**Comment by gthyagi** [comment]
This error occurred due to a bug in my Python virtual environment.
